# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold5_e5.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold6_e5.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold7_e5.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold8_e5.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold5

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold6

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold7

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold8

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold5

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold6

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold7

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold8



# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold5_e10.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold6_e10.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold7_e10.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold8_e10.txt

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold5

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold6

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold7

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold8

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold5

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold6

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold7

# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_expect_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_expect_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_expect_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_expect_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_expect_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_expect_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_expect_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_expect_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_tokens_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_tokens_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_tokens_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_tokens_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_tokens_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_tokens_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_tokens_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_tokens_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_all_tokens_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold8