# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./roberta-relevant-classification-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/relevant_classifcation_e20.txt
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_classification_partial_context_all.txt -val_data_path ./data/valid_classification_partial_context.txt  -test_data_path ./data/test_classification_partial_context.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./roberta-classification-partial-context-all-b16-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/classifcation_partial_context_all_b16_e10.txt
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_classification_partial_context_all.txt -val_data_path ./data/valid_classification_partial_context_all.txt  -test_data_path ./data/valid_classification_basic_output_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_basic_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_classification_partial_context_all.txt -val_data_path ./data/valid_classification_partial_context_all.txt  -test_data_path ./data/valid_classification_basic_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_basic_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_classification_partial_context_all.txt -val_data_path ./data/valid_classification_partial_context_all.txt  -test_data_path ./data/test_classification_basic_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16
# CUDA_VISIBLE_DEVICES=3 python gpt_classification.py -train_data_path ./data/train_classification_partial_context_all_gpt.txt -val_data_path ./data/valid_classification_partial_context_all_gpt.txt  -test_data_path ./data/valid_classification_partial_context_all_gpt.txt -model_path_or_name=gpt2-large -model_type gpt2 --do_train --do_eval -output_dir ./gpt-classification-partial-context-all-b16/ -tokenizer ./gpt-tokenizer/ -num_train_epochs 5 -batch_size 1 -max_len 150 -grad_accumulation 16 > ./train_outputs/gpt2_classifcation_partial_context_all_b16_e5.txt
# CUDA_VISIBLE_DEVICES=3 python gpt_classification.py -train_data_path ./data/train_classification_partial_context_all_gpt.txt -val_data_path ./data/valid_classification_partial_context_all_gpt.txt  -test_data_path ./data/valid_classification_partial_context_all_gpt.txt  -model_path_or_name=gpt2-large -model_type gpt2 --do_test -output_dir ./gpt-classification-partial-context-all-b16/ -tokenizer ./gpt-tokenizer/ -batch_size 1
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_ordered_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_ordered
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_direct_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_direct
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_describe_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_describe
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_expect_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_expect
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_tokens_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_tokens
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_all_tokens_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_all_tokens
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_ordered_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_ordered
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_direct_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_direct
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_describe_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_describe
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_expect_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_expect
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_tokens_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_tokens
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_relevant_classification_all_tokens_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_all_tokens
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_ordered_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_ordered
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_direct_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_direct
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_describe_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_describe
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_expect_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_expect
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_tokens_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_tokens
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_all_tokens_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename test_all_tokens
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_ordered_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_ordered
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_direct_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_direct
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_describe_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_describe
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_expect_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_expect
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_tokens_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_tokens
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/valid_classification_all_tokens_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename valid_all_tokens
# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_relevant_classification_new_scenarios_ordered.txt -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-relevant-classification-e10/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename new_scenarios_ordered
# CUDA_VISIBLE_DEVICES=3 python run_classification.py -train_data_path ./data/train_relevant_classification.txt -val_data_path ./data/valid_relevant_classification.txt  -test_data_path ./data/test_classification_new_scenarios_ordered_removed_deduplicated.txt -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./roberta-classification-partial-context-all-b16/epoch5/ -tokenizer ./roberta-tokenizer/ -batch_size 16 -filename new_scenarios_ordered

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold1_e5.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold2_e5.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold3_e5.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold4_e5.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold1_e10.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold2_e10.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold3_e10.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold4_e10.txt


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold1-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold1_e20.txt

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold2-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold2_e20.txt


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold3-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold3_e20.txt


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold4-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold4_e20.txt


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/valid_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/valid_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/valid_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/valid_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/valid_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/valid_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/valid_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/valid_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/valid_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/valid_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/valid_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/valid_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold4


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold8


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold8


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_new_scenarios_basic.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename new_scenarios_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_basic_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_expect_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename expect_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_direct_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_describe_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_ordered_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold8

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_tokens_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename tokens_fold8


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold1_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold1

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold2.txt -val_data_path ./data/folds/valid_relevant_classification_fold2.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold2_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold2

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold3.txt -val_data_path ./data/folds/valid_relevant_classification_fold3.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold3_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold3

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold4.txt -val_data_path ./data/folds/valid_relevant_classification_fold4.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold4_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold4

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold5_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold5

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold6_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold6

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold7_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold7

# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_all_tokens_fold8_output.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename all_tokens_fold8


# CUDA_VISIBLE_DEVICES=0 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold1.txt -val_data_path ./data/folds/valid_relevant_classification_fold1.txt  -test_data_path ./data/folds/test_relevant_classification_new_scenarios_basic.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename new_scenarios_fold1