# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold1_e5.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold2_e5.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold3_e5.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/classifcation_fold4_e5.txt



# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold1

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold2

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold3

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold4



# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold1

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold2

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold3

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold4


# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold1_e10.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold2_e10.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold3_e10.txt

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/classifcation_fold4_e10.txt


# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold1

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold2

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold3

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold4

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold1.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold1

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold2.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold2

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold3.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold3

# CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_partial_context_all_fold4.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_basic_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_basic_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_basic_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_basic_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_basic_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_basic_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_basic_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_basic_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename basic_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_ordered_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_ordered_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_ordered_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_ordered_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_ordered_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_ordered_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_ordered_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_ordered_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename ordered_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_direct_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_direct_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_direct_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_direct_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_direct_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_direct_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_direct_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_direct_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename direct_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_describe_fold1_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold1

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold2.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold2.txt  -test_data_path ./data/folds/test_classification_describe_fold2_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold2-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold2

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold3.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold3.txt  -test_data_path ./data/folds/test_classification_describe_fold3_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold3-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold3

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold4.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold4.txt  -test_data_path ./data/folds/test_classification_describe_fold4_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold4-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold4

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold5.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold5.txt  -test_data_path ./data/folds/test_classification_describe_fold5_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold5

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold6.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold6.txt  -test_data_path ./data/folds/test_classification_describe_fold6_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold6

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold7.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold7.txt  -test_data_path ./data/folds/test_classification_describe_fold7_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold7

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold8.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold8.txt  -test_data_path ./data/folds/test_classification_describe_fold8_output_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename describe_fold8

CUDA_VISIBLE_DEVICES=2 python run_classification.py -train_data_path ./data/folds/train_classification_partial_context_all_fold1.txt -val_data_path ./data/folds/valid_classification_partial_context_all_fold1.txt  -test_data_path ./data/folds/test_classification_new_scenarios_basic_large_fold1_g16_removed_deduplicated.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-classification-fold1-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename new_scenarios_fold1