# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold5_e5.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold6_e5.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold7_e5.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -num_train_epochs 5 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold8_e5.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold5_e10.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold6_e10.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold7_e10.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -num_train_epochs 10 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold8_e10.txt


# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold5-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold5_e20.txt

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold6-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold6_e20.txt


# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold7-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold7_e20.txt


# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_train --do_eval -output_dir ./folds/roberta-relevant-classification-fold8-e20 -tokenizer ./roberta-tokenizer/ -num_train_epochs 20 -batch_size 16 > ./train_outputs/folds/relevant_classifcation_fold8_e20.txt


# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/valid_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/valid_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/valid_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/valid_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold8

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/valid_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/valid_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/valid_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/valid_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold8

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/valid_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/valid_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/valid_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/valid_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename valid_fold8


# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e5 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold8

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e10 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold8

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold5.txt -val_data_path ./data/folds/valid_relevant_classification_fold5.txt  -test_data_path ./data/folds/test_relevant_classification_fold5.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold5-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold5

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold6.txt -val_data_path ./data/folds/valid_relevant_classification_fold6.txt  -test_data_path ./data/folds/test_relevant_classification_fold6.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold6-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold6

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold7.txt -val_data_path ./data/folds/valid_relevant_classification_fold7.txt  -test_data_path ./data/folds/test_relevant_classification_fold7.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold7-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold7

# CUDA_VISIBLE_DEVICES=1 python run_classification.py -train_data_path ./data/folds/train_relevant_classification_fold8.txt -val_data_path ./data/folds/valid_relevant_classification_fold8.txt  -test_data_path ./data/folds/test_relevant_classification_fold8.txt  -model_path_or_name=roberta-large -model_type roberta --do_test -output_dir ./folds/roberta-relevant-classification-fold8-e20 -tokenizer ./roberta-tokenizer/ -batch_size 16 --filename test_fold8
