# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/models_gptm_ordered --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_ordered.txt --do_eval --eval_data_file=../../scripts/data/valid_ordered.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --line_by_line > ../../scripts/train_outputs/lm_epoch1_ordered.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/models_gptm_expect --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_expect.txt --do_eval --eval_data_file=../../scripts/data/valid_expect.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --line_by_line > ../../scripts/train_outputs/lm_epoch1_expect.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_ordered --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_ordered_exp.txt > ../../scripts/outputs/generated_valid_ordered_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_expect --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_expect_exp.txt > ../../scripts/outputs/generated_valid_expect_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2-medium --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<|endoftext|>' --prompt=../../scripts/data/valid_expect_exp.txt > ../../scripts/outputs/generated_valid_pretrained_expect.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2-medium --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<|endoftext|>' --prompt=../../scripts/data/valid_ordered_exp.txt > ../../scripts/outputs/generated_valid_pretrained_ordered.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/models_gptm_basic_token --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_basic_token.txt --do_eval --eval_data_file=../../scripts/data/valid_basic_token.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --logging_dir=../logging/ --line_by_line > ../../scripts/train_outputs/lm_epoch1_basic_token.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_basic_token --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_exp.txt > ../../scripts/outputs/generated_valid_basic_token_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/models_gptl_ordered_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_ordered.txt --do_eval --eval_data_file=../../scripts/data/valid_ordered.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --overwrite_cache_dir --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/lm_large_epoch1_ordered_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ordered_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_ordered_exp.txt --output ../../scripts/outputs/generated_valid_ordered_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ordered_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/test_ordered.txt --output ../../scripts/outputs/generated_test_ordered_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/models_gptl_tokens_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_tokens.txt --do_eval --eval_data_file=../../scripts/data/valid_tokens.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/lm_large_epoch1_tokens_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_tokens_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_tokens_exp.txt --output ../../scripts/outputs/generated_valid_tokens_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_tokens_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/test_tokens.txt --output ../../scripts/outputs/generated_test_tokens_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold1_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold1_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold1_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold2_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold2_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold2_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold3_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold3_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold3_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold4_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold4_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold4_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold5_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold5_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold5_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold6_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold6_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold6_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold7_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold7_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold7_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_tokens_fold8_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_tokens_fold8_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_tokens_fold8_g16.txt
CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold1_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold1_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold1_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold2_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold2_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold2_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold3_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold3_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold3_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold4_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold4_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold4_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold5_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold5_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold5_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold6_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold6_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold6_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold7_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold7_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold7_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_all_tokens_fold8_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_all_tokens_fold8_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_all_tokens_fold8_g16.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold1_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold1.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold1_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold2_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold2.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold2_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold3_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold3.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold3_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold4_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold4.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold4_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold5_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold5.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold5_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold6_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold6.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold6_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold7_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold7.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold7_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_tokens_fold8_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold8.txt --output ../../scripts/outputs/folds/generated_test_tokens_large_fold8_g16_epoch1.txt
CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold1_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold1.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold1_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold2_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold2.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold2_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold3_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold3.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold3_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold4_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold4.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold4_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold5_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold5.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold5_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold6_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold6.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold6_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold7_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold7.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold7_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=2 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_all_tokens_fold8_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_tokens_fold8.txt --output ../../scripts/outputs/folds/generated_test_all_tokens_large_fold8_g16_epoch1.txt
