# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptm_direct --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_direct.txt --do_eval --eval_data_file=../../scripts/data/valid_direct.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --line_by_line > ../../scripts/train_outputs/lm_epoch1_direct.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptm_describe --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_describe.txt --do_eval --eval_data_file=../../scripts/data/valid_describe.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --line_by_line > ../../scripts/train_outputs/lm_epoch1_describe.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_direct --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_direct_exp.txt > ../../scripts/outputs/generated_valid_direct_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_describe --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_describe_exp.txt > ../../scripts/outputs/generated_valid_describe_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2-medium --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<|endoftext|>' --prompt=../../scripts/data/valid_describe_exp.txt > ../../scripts/outputs/generated_valid_pretrained_describe.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptm_ilm --model_type=gpt2 --model_name_or_path=gpt2-medium --do_train --train_data_file=../../scripts/data/train_ilm.txt --do_eval --eval_data_file=../../scripts/data/valid_ilm.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=2 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=8 --per_device_train_batch_size=8 --block_size=150  --logging_steps=100 --evaluate_during_training --line_by_line > ../../scripts/train_outputs/lm_epoch2_ilm.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptm_ilm --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_inference_ilm.txt > ../../scripts/outputs/generated_valid_ilm.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_basic_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train.txt --do_eval --eval_data_file=../../scripts/data/valid.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/lm_large_epoch1_basic_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_basic_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_exp.txt > ../../scripts/outputs/generated_valid_basic_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_ilm_num_masked_ga16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_ilm_num_masked.txt --do_eval --eval_data_file=../../scripts/data/valid_ilm_num_masked.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --gradient_accumulation_steps=16 --line_by_line > ../../scripts/train_outputs/lm_epoch1_ilm_num_masked_ga16.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ilm_num_masked_ga16 --length=15 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_inference_ilm_num_masked_subset.txt > ../../scripts/outputs/generated_valid_ilm_num_masked_subset_ga16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_ilm_ga8 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_ilm.txt --do_eval --eval_data_file=../../scripts/data/valid_ilm.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=2 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --gradient_accumulation_steps=8 --line_by_line > ../../scripts/train_outputs/lm_ilm_large_ga8_epoch2.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ilm_ga8 --length=15 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_inference_ilm_subset.txt > ../../scripts/outputs/generated_valid_ilm_large_ga8_epoch2_subset.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_ilm_num_ga8 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_ilm_num.txt --do_eval --eval_data_file=../../scripts/data/valid_ilm_num.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=2 --overwrite_output_dir --save_steps=100 --logging_dir=../logging/ --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --gradient_accumulation_steps=8 --line_by_line > ../../scripts/train_outputs/lm_ilm_num_large_ga8_epoch2.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ilm_num_ga8 --length=15 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_inference_ilm_num_subset.txt --output=../../scripts/outputs/generated_valid_large_ilm_num_ga8_epoch2_subset.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_basic_g16 --length=150 --k=50 --num_return_sequences=15 --sample --stop_token='<EOS>' --prompt=../../scripts/data/scenario.txt --output=../../scripts/outputs/generated_scenarios_basic.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_scenario_ga8 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_scenario.txt --do_eval --eval_data_file=../../scripts/data/valid_scenario.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=10 --logging_dir=../logging/ --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=15  --logging_steps=10 --evaluate_during_training --gradient_accumulation_steps=8 --line_by_line > ../../scripts/train_outputs/lm_large_scenario_e1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_scenario_ga8 --length=15 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/scenario.txt --output=../../scripts/outputs/generated_scenarios_new_basic.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_ordered_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/new_scenarios.txt --output=../../scripts/outputs/generated_new_scenarios_ordered.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=gpt2-large --length=150 --k=50 --num_return_sequences=5 --sample --prompt=../../scripts/data/test_pretrained.txt --output=../../scripts/outputs/generated_pretrained_large_titlecase.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/models_gptl_direct_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/train_direct.txt --do_eval --eval_data_file=../../scripts/data/valid_direct.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --evaluate_during_training --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/lm_large_epoch1_direct_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_direct_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/valid_direct_exp.txt --output ../../scripts/outputs/generated_valid_direct_large_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/models_gptl_direct_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/test_direct.txt --output ../../scripts/outputs/generated_test_direct_large_g16_epoch1.txt


# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold1_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold1_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold1_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold2_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold2_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold2_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold3_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold3_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold3_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold4_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold4_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold4_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold5_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold5_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold5_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold6_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold6_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold6_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold7_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold7_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold7_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_basic_fold8_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_basic_fold8_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_basic_fold8_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold1_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold1_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold1_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold2_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold2_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold2_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold3_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold3_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold3_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold4_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold4_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold4_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold5_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold5_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold5_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold6_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold6_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold6_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold7_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold7_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold7_g16.txt
# CUDA_VISIBLE_DEVICES=0 python run_language_modeling.py --output_dir=../../scripts/folds/models_gptl_ordered_fold8_g16 --model_type=gpt2 --model_name_or_path=gpt2-large --do_train --train_data_file=../../scripts/data/folds/train_ordered_fold8_shuf.txt --tokenizer=../../scripts/gpt-tokenizer --num_train_epochs=1 --overwrite_output_dir --save_steps=100 --per_device_eval_batch_size=1 --per_device_train_batch_size=1 --block_size=150  --logging_steps=100 --logging_dir=../logging/ --line_by_line --gradient_accumulation_steps=16 > ../../scripts/train_outputs/folds/lm_large_epoch1_ordered_fold8_g16.txt

# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold1_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold1.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold1_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold2_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold2.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold2_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold3_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold3.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold3_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold4_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold4.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold4_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold5_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold5.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold5_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold6_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold6.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold6_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold7_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold7.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold7_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold8_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_basic_fold8.txt --output ../../scripts/outputs/folds/generated_test_basic_large_fold8_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold1_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold1.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold1_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold2_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold2.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold2_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold3_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold3.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold3_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold4_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold4.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold4_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold5_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold5.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold5_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold6_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold6.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold6_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold7_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold7.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold7_g16_epoch1.txt
# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_ordered_fold8_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/folds/test_ordered_fold8.txt --output ../../scripts/outputs/folds/generated_test_ordered_large_fold8_g16_epoch1.txt

# CUDA_VISIBLE_DEVICES=0 python run_generation.py --model_type=gpt2 --model_name_or_path=../../scripts/folds/models_gptl_basic_fold1_g16 --length=150 --k=50 --num_return_sequences=5 --sample --stop_token='<EOS>' --prompt=../../scripts/data/new_scenarios.txt --output ../../scripts/outputs/folds/generated_new_scenarios_basic_large_fold1_g16_epoch1.txt